# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170424_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landowner',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landowner',
            name='place',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
