# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170424_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carowner',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='carowner',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
