# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170424_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='landowner',
            name='place',
        ),
        migrations.AddField(
            model_name='landowner',
            name='earnings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landowner',
            name='placename',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='place',
            name='placename',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.LandOwner'),
        ),
    ]
