# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170424_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landowner',
            name='placename',
        ),
        migrations.AddField(
            model_name='landowner',
            name='p',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
