# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170424_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landowner',
            old_name='p',
            new_name='placename',
        ),
    ]
