# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170424_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='vacancy',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
