# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_place_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='pincode',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
