# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 03:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170426_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
