# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170426_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='earnings',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
